package com.tc.utils.variables.enums

enum class ActionType {
    ACTION_EXPLORE,
    ACTION_UPDATE_STATUS,
    ACTION_CANCEL,
    ACTION_UPLOAD,
    ACTION_ADD,
    ACTION_REMOVE,
    ACTION_LOGOUT,
    ACTION_PRIVACY_POLICY,
    ACTION_RATE,
    ACTION_DELETE,
    ACTION_SHARE,
    ACTION_CAMERA,
    ACTION_GALLERY,
    DACHSHUND,
    ACTION_CONTACT,
}
